version: "3.8"

services:
  app:
    tty: true
    stdin_open: true
    image: node:15
    command: yarn start
    ports:
      - 3050:3050
    working_dir: /app
    volumes:
      - ./:/app

  test:
    tty: true
    stdin_open: true
    image: node:15
    command: yarn test
    working_dir: /app
    volumes:
      - ./:/app
