version: "3.8"

services:
  app:
    tty: true
    stdin_open: true
    image: node:15
    command: yarn start
    ports:
      - 3050:3050
    working_dir: /app
    volumes:
      - ./:/app

  node-service:
    tty: true
    stdin_open: true
    image: node:15
    working_dir: /app
    volumes:
      - ./:/app

  node-prod:
    tty: true
    stdin_open: true
    image: node:15-alpine3.10
    working_dir: /app
    environment:
      - CI=true
    volumes:
      - ./:/app
